server:
  port: 8090
spring:
  data:
    mongodb:
      username: rajdip14
      password: rajdip14
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
